// This file is auto-generated by scripts/generate-sitemap-lastmod.mjs
// Do not edit manually.

export const sitemapLastmodMap: Record<string, string> = {
  "/": "2026-02-15T12:06:55+01:00",
  "/privacy-policy": "2026-02-15T12:06:55+01:00",
  "/tos": "2026-02-15T12:06:55+01:00"
}
