// This file is auto-generated by scripts/generate-sitemap-lastmod.mjs
// Do not edit manually.

export const sitemapLastmodMap: Record<string, string> = {
  "/": "2026-02-28T23:20:01+01:00",
  "/discord-communities": "2026-02-28T23:20:01+01:00",
  "/open-source": "2026-02-28T23:20:01+01:00",
  "/indie-games": "2026-02-28T23:20:01+01:00",
  "/agencies": "2026-02-28T23:20:01+01:00",
  "/non-technical-founders": "2026-02-28T23:20:01+01:00",
  "/privacy-policy": "2026-02-28T23:20:01+01:00",
  "/tos": "2026-02-28T23:20:01+01:00"
}
